### ISSUE TITLE
[Bug] Nav bar goes over screen.

### ISSUE THREAD

**Issue by poppindouble** [kaist-cp/kaist-cp.github.io#88]
Browser: Firefox version 95.0

Bug: 
1. Font size in navigation bar is too big that it goes off the screen, leading to a horizontal scroll bar at the bottom.
2. Font size is too big on Firefox.
3. It works on Chromium Version 96.0.4664.45, there is no bug on chrome  iOS app too.

Reason:
I think the bug comes from jekyll itself.
On Chrome, jekyll use `-webkit-text-size-adjust: 100%;` for the whole `html`. But this property is not capable with Firefox, in Firefox we need to use `font-size-adjust: 0.45`. 

I tried for a while to fix the bug but I can't get it work....I am opening this issue just let other's know.

**Comment by jeehoonkang** [comment]
Thanks for the report. Would you please paste a picture? It seems it works for me (Firefox on Linux).

**Comment by poppindouble** [comment]
![bug](https://user-images.githubusercontent.com/6710426/147420895-bb7f4a95-34ef-43ef-ad96-2adecea847e5.png)

- First photo is the bug, look at the top menu bar, `contatct` goes over the screen.

![no=bug](https://user-images.githubusercontent.com/6710426/147420899-f584ecf7-75ee-4edc-bffd-c8858bd876ae.png)

- I fixed it with `font-size-adjust: 0.45`.

![90%](https://user-images.githubusercontent.com/6710426/147420917-018f33ce-1832-4daa-95cb-dd2aa2710f81.png)

- If you use `ctrl + -` to shrink the whole web to 90% initial view point, it kinda of works.

Sorry about the second screen in photo 2 and photo 3, it is redundant.

**Comment by jeehoonkang** [comment]
I think now it's resolved. thanks!
