### ISSUE TITLE
Create personal websites

### ISSUE THREAD

**Issue by JiseungHong** [kaist-cp/kaist-cp.github.io#9]
This is a meta issue on personal websites.

**Comment by JiseungHong** [comment]
Remove TODOs

**Comment by jeehoonkang** [comment]
Please make your website in this repository, following the instruction here: https://github.com/kaist-cp/kaist-cp#first-things-to-do

- [ ] @JiseungHong
- [ ] @hydium
- [ ] @tomtomjhj

**Comment by jeehoonkang** [comment]
@tomtomjhj Please make your website!
